//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace Traderdata.Client.TerminalWEB.SoaMD {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CotacaoServerDTO", Namespace="http://schemas.datacontract.org/2004/07/Traderdata.Server.Core.DTO")]
    public partial class CotacaoServerDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double AberturaField;
        
        private bool AfterMarketField;
        
        private System.DateTime DataField;
        
        private string HoraField;
        
        private double MaximoField;
        
        private double MinimoField;
        
        private double QuantidadeField;
        
        private double UltimoField;
        
        private double VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Abertura {
            get {
                return this.AberturaField;
            }
            set {
                if ((this.AberturaField.Equals(value) != true)) {
                    this.AberturaField = value;
                    this.RaisePropertyChanged("Abertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AfterMarket {
            get {
                return this.AfterMarketField;
            }
            set {
                if ((this.AfterMarketField.Equals(value) != true)) {
                    this.AfterMarketField = value;
                    this.RaisePropertyChanged("AfterMarket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Maximo {
            get {
                return this.MaximoField;
            }
            set {
                if ((this.MaximoField.Equals(value) != true)) {
                    this.MaximoField = value;
                    this.RaisePropertyChanged("Maximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Minimo {
            get {
                return this.MinimoField;
            }
            set {
                if ((this.MinimoField.Equals(value) != true)) {
                    this.MinimoField = value;
                    this.RaisePropertyChanged("Minimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Ultimo {
            get {
                return this.UltimoField;
            }
            set {
                if ((this.UltimoField.Equals(value) != true)) {
                    this.UltimoField = value;
                    this.RaisePropertyChanged("Ultimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Volume {
            get {
                return this.VolumeField;
            }
            set {
                if ((this.VolumeField.Equals(value) != true)) {
                    this.VolumeField = value;
                    this.RaisePropertyChanged("Volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.traderdata.com.br", ConfigurationName="SoaMD.IMarketDataTerminalWeb")]
    public interface IMarketDataTerminalWeb {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.traderdata.com.br/IMarketDataTerminalWeb/GetAtivos", ReplyAction="www.traderdata.com.br/IMarketDataTerminalWeb/GetAtivosResponse")]
        System.IAsyncResult BeginGetAtivos(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetAtivos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.traderdata.com.br/IMarketDataTerminalWeb/GetAtivosCompactado", ReplyAction="www.traderdata.com.br/IMarketDataTerminalWeb/GetAtivosCompactadoResponse")]
        System.IAsyncResult BeginGetAtivosCompactado(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetAtivosCompactado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.traderdata.com.br/IMarketDataTerminalWeb/GetAtivo", ReplyAction="www.traderdata.com.br/IMarketDataTerminalWeb/GetAtivoResponse")]
        System.IAsyncResult BeginGetAtivo(string ativo, System.AsyncCallback callback, object asyncState);
        
        string EndGetAtivo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.traderdata.com.br/IMarketDataTerminalWeb/GetHistoricoBovespa", ReplyAction="www.traderdata.com.br/IMarketDataTerminalWeb/GetHistoricoBovespaResponse")]
        System.IAsyncResult BeginGetHistoricoBovespa(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> EndGetHistoricoBovespa(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="www.traderdata.com.br/IMarketDataTerminalWeb/GetHistoricoBMF", ReplyAction="www.traderdata.com.br/IMarketDataTerminalWeb/GetHistoricoBMFResponse")]
        System.IAsyncResult BeginGetHistoricoBMF(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> EndGetHistoricoBMF(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMarketDataTerminalWebChannel : Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAtivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAtivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAtivosCompactadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAtivosCompactadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAtivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAtivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHistoricoBovespaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHistoricoBovespaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHistoricoBMFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetHistoricoBMFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MarketDataTerminalWebClient : System.ServiceModel.ClientBase<Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb>, Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb {
        
        private BeginOperationDelegate onBeginGetAtivosDelegate;
        
        private EndOperationDelegate onEndGetAtivosDelegate;
        
        private System.Threading.SendOrPostCallback onGetAtivosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAtivosCompactadoDelegate;
        
        private EndOperationDelegate onEndGetAtivosCompactadoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAtivosCompactadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAtivoDelegate;
        
        private EndOperationDelegate onEndGetAtivoDelegate;
        
        private System.Threading.SendOrPostCallback onGetAtivoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHistoricoBovespaDelegate;
        
        private EndOperationDelegate onEndGetHistoricoBovespaDelegate;
        
        private System.Threading.SendOrPostCallback onGetHistoricoBovespaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetHistoricoBMFDelegate;
        
        private EndOperationDelegate onEndGetHistoricoBMFDelegate;
        
        private System.Threading.SendOrPostCallback onGetHistoricoBMFCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MarketDataTerminalWebClient() {
        }
        
        public MarketDataTerminalWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MarketDataTerminalWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataTerminalWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MarketDataTerminalWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAtivosCompletedEventArgs> GetAtivosCompleted;
        
        public event System.EventHandler<GetAtivosCompactadoCompletedEventArgs> GetAtivosCompactadoCompleted;
        
        public event System.EventHandler<GetAtivoCompletedEventArgs> GetAtivoCompleted;
        
        public event System.EventHandler<GetHistoricoBovespaCompletedEventArgs> GetHistoricoBovespaCompleted;
        
        public event System.EventHandler<GetHistoricoBMFCompletedEventArgs> GetHistoricoBMFCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.BeginGetAtivos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAtivos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.EndGetAtivos(System.IAsyncResult result) {
            return base.Channel.EndGetAtivos(result);
        }
        
        private System.IAsyncResult OnBeginGetAtivos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).BeginGetAtivos(callback, asyncState);
        }
        
        private object[] OnEndGetAtivos(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).EndGetAtivos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAtivosCompleted(object state) {
            if ((this.GetAtivosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAtivosCompleted(this, new GetAtivosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAtivosAsync() {
            this.GetAtivosAsync(null);
        }
        
        public void GetAtivosAsync(object userState) {
            if ((this.onBeginGetAtivosDelegate == null)) {
                this.onBeginGetAtivosDelegate = new BeginOperationDelegate(this.OnBeginGetAtivos);
            }
            if ((this.onEndGetAtivosDelegate == null)) {
                this.onEndGetAtivosDelegate = new EndOperationDelegate(this.OnEndGetAtivos);
            }
            if ((this.onGetAtivosCompletedDelegate == null)) {
                this.onGetAtivosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAtivosCompleted);
            }
            base.InvokeAsync(this.onBeginGetAtivosDelegate, null, this.onEndGetAtivosDelegate, this.onGetAtivosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.BeginGetAtivosCompactado(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAtivosCompactado(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.EndGetAtivosCompactado(System.IAsyncResult result) {
            return base.Channel.EndGetAtivosCompactado(result);
        }
        
        private System.IAsyncResult OnBeginGetAtivosCompactado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).BeginGetAtivosCompactado(callback, asyncState);
        }
        
        private object[] OnEndGetAtivosCompactado(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).EndGetAtivosCompactado(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAtivosCompactadoCompleted(object state) {
            if ((this.GetAtivosCompactadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAtivosCompactadoCompleted(this, new GetAtivosCompactadoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAtivosCompactadoAsync() {
            this.GetAtivosCompactadoAsync(null);
        }
        
        public void GetAtivosCompactadoAsync(object userState) {
            if ((this.onBeginGetAtivosCompactadoDelegate == null)) {
                this.onBeginGetAtivosCompactadoDelegate = new BeginOperationDelegate(this.OnBeginGetAtivosCompactado);
            }
            if ((this.onEndGetAtivosCompactadoDelegate == null)) {
                this.onEndGetAtivosCompactadoDelegate = new EndOperationDelegate(this.OnEndGetAtivosCompactado);
            }
            if ((this.onGetAtivosCompactadoCompletedDelegate == null)) {
                this.onGetAtivosCompactadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAtivosCompactadoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAtivosCompactadoDelegate, null, this.onEndGetAtivosCompactadoDelegate, this.onGetAtivosCompactadoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.BeginGetAtivo(string ativo, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAtivo(ativo, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.EndGetAtivo(System.IAsyncResult result) {
            return base.Channel.EndGetAtivo(result);
        }
        
        private System.IAsyncResult OnBeginGetAtivo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ativo = ((string)(inValues[0]));
            return ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).BeginGetAtivo(ativo, callback, asyncState);
        }
        
        private object[] OnEndGetAtivo(System.IAsyncResult result) {
            string retVal = ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).EndGetAtivo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAtivoCompleted(object state) {
            if ((this.GetAtivoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAtivoCompleted(this, new GetAtivoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAtivoAsync(string ativo) {
            this.GetAtivoAsync(ativo, null);
        }
        
        public void GetAtivoAsync(string ativo, object userState) {
            if ((this.onBeginGetAtivoDelegate == null)) {
                this.onBeginGetAtivoDelegate = new BeginOperationDelegate(this.OnBeginGetAtivo);
            }
            if ((this.onEndGetAtivoDelegate == null)) {
                this.onEndGetAtivoDelegate = new EndOperationDelegate(this.OnEndGetAtivo);
            }
            if ((this.onGetAtivoCompletedDelegate == null)) {
                this.onGetAtivoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAtivoCompleted);
            }
            base.InvokeAsync(this.onBeginGetAtivoDelegate, new object[] {
                        ativo}, this.onEndGetAtivoDelegate, this.onGetAtivoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.BeginGetHistoricoBovespa(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHistoricoBovespa(ativo, periodicidade, numeroDias, ajuste, afterMarket, delay, dataHoraUltimaBarra, guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.EndGetHistoricoBovespa(System.IAsyncResult result) {
            return base.Channel.EndGetHistoricoBovespa(result);
        }
        
        private System.IAsyncResult OnBeginGetHistoricoBovespa(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ativo = ((string)(inValues[0]));
            int periodicidade = ((int)(inValues[1]));
            int numeroDias = ((int)(inValues[2]));
            bool ajuste = ((bool)(inValues[3]));
            bool afterMarket = ((bool)(inValues[4]));
            bool delay = ((bool)(inValues[5]));
            System.DateTime dataHoraUltimaBarra = ((System.DateTime)(inValues[6]));
            string guid = ((string)(inValues[7]));
            return ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).BeginGetHistoricoBovespa(ativo, periodicidade, numeroDias, ajuste, afterMarket, delay, dataHoraUltimaBarra, guid, callback, asyncState);
        }
        
        private object[] OnEndGetHistoricoBovespa(System.IAsyncResult result) {
            System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> retVal = ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).EndGetHistoricoBovespa(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHistoricoBovespaCompleted(object state) {
            if ((this.GetHistoricoBovespaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHistoricoBovespaCompleted(this, new GetHistoricoBovespaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHistoricoBovespaAsync(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid) {
            this.GetHistoricoBovespaAsync(ativo, periodicidade, numeroDias, ajuste, afterMarket, delay, dataHoraUltimaBarra, guid, null);
        }
        
        public void GetHistoricoBovespaAsync(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, object userState) {
            if ((this.onBeginGetHistoricoBovespaDelegate == null)) {
                this.onBeginGetHistoricoBovespaDelegate = new BeginOperationDelegate(this.OnBeginGetHistoricoBovespa);
            }
            if ((this.onEndGetHistoricoBovespaDelegate == null)) {
                this.onEndGetHistoricoBovespaDelegate = new EndOperationDelegate(this.OnEndGetHistoricoBovespa);
            }
            if ((this.onGetHistoricoBovespaCompletedDelegate == null)) {
                this.onGetHistoricoBovespaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHistoricoBovespaCompleted);
            }
            base.InvokeAsync(this.onBeginGetHistoricoBovespaDelegate, new object[] {
                        ativo,
                        periodicidade,
                        numeroDias,
                        ajuste,
                        afterMarket,
                        delay,
                        dataHoraUltimaBarra,
                        guid}, this.onEndGetHistoricoBovespaDelegate, this.onGetHistoricoBovespaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.BeginGetHistoricoBMF(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetHistoricoBMF(ativo, periodicidade, numeroDias, ajuste, afterMarket, delay, dataHoraUltimaBarra, guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb.EndGetHistoricoBMF(System.IAsyncResult result) {
            return base.Channel.EndGetHistoricoBMF(result);
        }
        
        private System.IAsyncResult OnBeginGetHistoricoBMF(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ativo = ((string)(inValues[0]));
            int periodicidade = ((int)(inValues[1]));
            int numeroDias = ((int)(inValues[2]));
            bool ajuste = ((bool)(inValues[3]));
            bool afterMarket = ((bool)(inValues[4]));
            bool delay = ((bool)(inValues[5]));
            System.DateTime dataHoraUltimaBarra = ((System.DateTime)(inValues[6]));
            string guid = ((string)(inValues[7]));
            return ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).BeginGetHistoricoBMF(ativo, periodicidade, numeroDias, ajuste, afterMarket, delay, dataHoraUltimaBarra, guid, callback, asyncState);
        }
        
        private object[] OnEndGetHistoricoBMF(System.IAsyncResult result) {
            System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> retVal = ((Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb)(this)).EndGetHistoricoBMF(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetHistoricoBMFCompleted(object state) {
            if ((this.GetHistoricoBMFCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetHistoricoBMFCompleted(this, new GetHistoricoBMFCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetHistoricoBMFAsync(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid) {
            this.GetHistoricoBMFAsync(ativo, periodicidade, numeroDias, ajuste, afterMarket, delay, dataHoraUltimaBarra, guid, null);
        }
        
        public void GetHistoricoBMFAsync(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, object userState) {
            if ((this.onBeginGetHistoricoBMFDelegate == null)) {
                this.onBeginGetHistoricoBMFDelegate = new BeginOperationDelegate(this.OnBeginGetHistoricoBMF);
            }
            if ((this.onEndGetHistoricoBMFDelegate == null)) {
                this.onEndGetHistoricoBMFDelegate = new EndOperationDelegate(this.OnEndGetHistoricoBMF);
            }
            if ((this.onGetHistoricoBMFCompletedDelegate == null)) {
                this.onGetHistoricoBMFCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHistoricoBMFCompleted);
            }
            base.InvokeAsync(this.onBeginGetHistoricoBMFDelegate, new object[] {
                        ativo,
                        periodicidade,
                        numeroDias,
                        ajuste,
                        afterMarket,
                        delay,
                        dataHoraUltimaBarra,
                        guid}, this.onEndGetHistoricoBMFDelegate, this.onGetHistoricoBMFCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb CreateChannel() {
            return new MarketDataTerminalWebClientChannel(this);
        }
        
        private class MarketDataTerminalWebClientChannel : ChannelBase<Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb>, Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb {
            
            public MarketDataTerminalWebClientChannel(System.ServiceModel.ClientBase<Traderdata.Client.TerminalWEB.SoaMD.IMarketDataTerminalWeb> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAtivos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAtivos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetAtivos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetAtivos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAtivosCompactado(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAtivosCompactado", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetAtivosCompactado(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetAtivosCompactado", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAtivo(string ativo, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ativo;
                System.IAsyncResult _result = base.BeginInvoke("GetAtivo", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetAtivo(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetAtivo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetHistoricoBovespa(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = ativo;
                _args[1] = periodicidade;
                _args[2] = numeroDias;
                _args[3] = ajuste;
                _args[4] = afterMarket;
                _args[5] = delay;
                _args[6] = dataHoraUltimaBarra;
                _args[7] = guid;
                System.IAsyncResult _result = base.BeginInvoke("GetHistoricoBovespa", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> EndGetHistoricoBovespa(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> _result = ((System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO>)(base.EndInvoke("GetHistoricoBovespa", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetHistoricoBMF(string ativo, int periodicidade, int numeroDias, bool ajuste, bool afterMarket, bool delay, System.DateTime dataHoraUltimaBarra, string guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = ativo;
                _args[1] = periodicidade;
                _args[2] = numeroDias;
                _args[3] = ajuste;
                _args[4] = afterMarket;
                _args[5] = delay;
                _args[6] = dataHoraUltimaBarra;
                _args[7] = guid;
                System.IAsyncResult _result = base.BeginInvoke("GetHistoricoBMF", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> EndGetHistoricoBMF(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO> _result = ((System.Collections.Generic.List<Traderdata.Client.TerminalWEB.SoaMD.CotacaoServerDTO>)(base.EndInvoke("GetHistoricoBMF", _args, result)));
                return _result;
            }
        }
    }
}
